"""Initial migration

Revision ID: d2374fc10340
Revises: 
Create Date: 2025-02-22 08:38:14.880221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2374fc10340'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('location_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('product_movement',
    sa.Column('movement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('from_location', sa.String(length=50), nullable=True),
    sa.Column('to_location', sa.String(length=50), nullable=True),
    sa.Column('product_id', sa.String(length=50), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_location'], ['location.location_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['to_location'], ['location.location_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_movement')
    op.drop_table('product')
    op.drop_table('location')
    # ### end Alembic commands ###
